FROM docker.intuit.com/oicp/standard/maven/amzn-maven-corretto11:latest AS build

# USER root needed for build, since CPD does not allow root user for gold images.
# intermediate containers will be discarded at final stage, runtime image will be executed with non root user
USER root
# Get ARG for sonar
ARG sonar
# Copy sonar script & bundle
COPY sonar-analysis.sh /sonar-analysis.sh
COPY bundle /usr/src/bundle

# Run Code Analysis
WORKDIR /usr/src/bundle
RUN bash -x /sonar-analysis.sh
