
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: jobrunr
  config:
    use-legacy-processing: true



# To disable Open API UI endpoints in PROD, uncomment the following in PROD profile
# springdoc:
#  api-docs:
#   enabled: false
#  swagger-ui:
#   enabled: false

jsk:
  lastmile:
    enabled: false
service:
  index:
    iks: true

# Configuration of TLS Termination in service layer
server:
  max-http-header-size: 32KB
  port: 8443 # Set it to 8080 or some other value, if running in clear text mode
  include-debug-info: false
  error:
    include-message: always # Might leak info if exceptions are sent as part of the error message
  ssl:
    enabled: true # Set to false to run in clear text mode, be sure to set 'service_layer_tls_termination' to no in entry.sh
#    enabled-protocols: TLSv1.1
    key-alias: tomcat
    key-store: /app/tmp/keystore.pkcs12
    key-store-password: ${TLS_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
