# Required in order to run in TLS locally
server:
  port: 8443
  include-debug-info: true
  error:
    include-message: always
  ssl:
    enabled: true
    enabled-protocols: TLSv1.2
    key-alias: local
    key-store: local-keystore/keystore.pkcs12
    key-store-password: local-keystore-password
    key-store-type: PKCS12

spring:
  data:
    mongodb:
      hostname: localhost
      database: jobrunr
      port: 27017
      username: "username"
      password: "password"
      min-pool-size: 10
      max-pool-size: 50

org:
  jobrunr:
    background-job-server:
      enabled: true
      worker-count: 10
      poll-interval-in-seconds: 60
    dashboard:
      enabled: true