jsk:
  lastmile:
    enabled: false
  mesh:
    enabled: true
    port: ${MESH_TRAFFIC_PORT}
security:
  intuit:
    cookies:
      enabled: false
    iamTicketFlowEnabled: true
    authZFlowEnabled: false

environment: prf
authz:
  config:
    connectingEnvironment: prf

spring:
  data:
    mongodb:
      hostname: scheduler-docdb-prf.cluster-ccmjg31hu82n.us-west-2.docdb.amazonaws.com
      database: jobrunr
      port: 27017
      min-pool-size: 10
      max-pool-size: 50

org:
  jobrunr:
    background-job-server:
      enabled: true
      worker-count: 10
      poll-interval-in-seconds: 60
    dashboard:
      enabled: true